version: "3.6"
services:
   db:
      image: mongo:latest
      container_name: interamtdb-mongo
      restart: always
      ports:
         - 27017:27017
      environment:
         - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb-user
         - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb-pass
      secrets:
         - mongodb-user
         - mongodb-pass
      volumes:
         - ./interamtdb-data:/data/db
volumes:
  interamtdb-data:
secrets:
   mongodb-user:
      file: ./.secrets/mongodb_user.txt
   mongodb-pass:
      file: ./.secrets/mongodb_pwd.txt